#!/bin/bash
#
# apache installeerimis skript
#
# kontrollime kas apache on paigaldatud 
Apache2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c 'ok installed')
if [ $Apache2 -eq 0 ]
then 
echo "Paigaldame apache2"
apt-get install -y apache2;
elif [ $Apache2 -eq 1 ]
then
echo "apache2 on paigaldatud edukalt!"
service apache2 status
fi
